"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_blue)\
$os\
$username\
[](bg:color_purple fg:color_blue)\
$directory\
[](fg:color_purple bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_cyan)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$ruby\
$perl\
$dart\
$elixir\
$elm\
$julia\
$nim\
$scala\
$swift\
$zig\
$ocaml\
$rlang\
$crystal\
$fennel\
$fortran\
$haxe\
$bun\
$deno\
[](fg:color_cyan bg:color_orange)\
$docker_context\
$conda\
$pixi\
[](fg:color_orange bg:color_bg3)\
$cmd_duration\
$status\
[ ](fg:color_bg3)\
$line_break$character"""

palette = 'solarized-osaka'

[palettes.tokyonight]
color_fg0 = '#15161e'
color_fg1 = '#c0caf5'
color_bg1 = '#1a1b26'
color_bg3 = '#414868'
color_blue = '#7aa2f7'
color_cyan = '#7dcfff'
color_teal = '#73daca'
color_green = '#9ece6a'
color_yellow = '#e0af68'
color_orange = '#ff9e64'
color_red = '#f7768e'
color_purple = '#bb9af7'

[palettes.solarized-osaka]
color_fg0 = '#001419'
color_fg1 = '#839395'
color_bg1 = '#001419'
color_bg3 = '#002c38'
color_blue = '#268bd3'
color_cyan = '#29a298'
color_teal = '#2aeddd'
color_green = '#849900'
color_yellow = '#b28500'
color_orange = '#c94c16'
color_red = '#db302d'
color_purple = '#6d71c4'

[os]
disabled = false
style = "bg:color_blue fg:color_fg0"
format = "[ $symbol]($style)"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[username]
show_always = true
style_user = "bg:color_blue fg:color_fg0"
style_root = "bg:color_blue fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
ssh_symbol = " "

[directory]
style = "fg:color_fg0 bg:color_purple"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false
repo_root_style = "fg:color_fg0 bg:color_purple"
before_repo_root_style = "fg:#576d74 bg:color_purple"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_green)]($style)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[git_commit]
tag_symbol = '  '

[nodejs]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[c]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[cpp]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[rust]
symbol = "󱘗 "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[golang]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[php]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[java]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[kotlin]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[haskell]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[python]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[docker_context]
symbol = " "
style = "bg:color_orange"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_orange)]($style)'

[conda]
symbol = " "
style = "bg:color_orange"
format = '[[ $symbol( $environment) ](fg:color_fg0 bg:color_orange)]($style)'

[pixi]
symbol = "󰏗 "
style = "bg:color_orange"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_orange)]($style)'

[cmd_duration]
min_time = 0
show_milliseconds = true
style = "bg:color_bg3"
format = '[[  $duration ](fg:color_fg1 bg:color_bg3)]($style)'

[status]
disabled = false
style = "bg:color_red"
map_symbol = true
format = '[[](fg:color_red bg:color_bg3)[ ✘ $common_meaning$signal_name ](fg:color_fg0 bg:color_red)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[cmake]
symbol = " "

[crystal]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[dart]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[deno]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[elixir]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[elm]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[fennel]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[fortran]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haxe]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[hg_branch]
symbol = " "

[julia]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[lua]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[nix_shell]
symbol = " "

[ocaml]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[package]
symbol = "󰏗 "

[perl]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[ruby]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[scala]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'
[swift]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'

[xmake]
symbol = " "

[zig]
symbol = " "
style = "bg:color_cyan"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_cyan)]($style)'
